Private Event Project
Zubenna/private-events pull request #3
Opened 2020-09-25 13:18 UTC by Zubenna

2020-09-26 02:41 UTC, voscarmv requested changes
# Nice work so far, team. 👍 
## However, there are some changes required 👀 🧰 🔨 🔧 

I cannot begin to review your project as the migrations are broken. Please roll back all migrations and try to migrate again. You should see the following error when you attempt to `rails rb:migrate`:

```
oscar@orion:~/tse/private-events$ rails db:migrate
== 20200909115024 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0021s
== 20200909115024 CreateUsers: migrated (0.0022s) =============================

== 20200909160515 CreateAttendances: migrating ================================
-- create_table(:attendances)
   -> 0.0208s
== 20200909160515 CreateAttendances: migrated (0.0210s) =======================

== 20200910014556 RemovePasswordFromUsers: migrating ==========================
-- remove_column(:users, :password, :string)
   -> 0.0413s
== 20200910014556 RemovePasswordFromUsers: migrated (0.0414s) =================

== 20200911221320 CreateEvents: migrating =====================================
-- create_table(:events)
   -> 0.0127s
== 20200911221320 CreateEvents: migrated (0.0133s) ============================

== 20200922121434 AddAttendances: migrating ===================================
-- create_table(:attendances)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: table "attendances" already exists
/home/oscar/tse/private-events/db/migrate/20200922121434_add_attendances.rb:3:in `change'
/home/oscar/tse/private-events/bin/rails:9:in `<top (required)>'
/home/oscar/tse/private-events/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: SQLite3::SQLException: table "attendances" already exists
/home/oscar/tse/private-events/db/migrate/20200922121434_add_attendances.rb:3:in `change'
/home/oscar/tse/private-events/bin/rails:9:in `<top (required)>'
/home/oscar/tse/private-events/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
SQLite3::SQLException: table "attendances" already exists
/home/oscar/tse/private-events/db/migrate/20200922121434_add_attendances.rb:3:in `change'
/home/oscar/tse/private-events/bin/rails:9:in `<top (required)>'
/home/oscar/tse/private-events/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Once you fix this it will be possible for the next TSE to review your code.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-09-27 05:35 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: :stop_sign: 
### HELLO  :wave:  @Zubenna GREAT PROGRESS SO FAR. HOWEVER, THERE ARE A FEW CHANGES THAT NEED TO BE MADE KINDLY CHECK BELOW :arrow_down: 

- [ ] The application is creating a user :+1:  However, there seems to be a problem in your event Create method. This is because the data is not getting persisted to the database.

![something](https://user-images.githubusercontent.com/32361963/94356809-2f64d400-009b-11eb-951f-a132e9a9e5a0.png)

- [ ] There should be navigation links at the top of the page.
![navigation](https://user-images.githubusercontent.com/32361963/94356848-a13d1d80-009b-11eb-8623-81e4c31d7ca9.png)

###NB once you fix the above suggestions the next TSE will be able to actually review your project

### If you have any questions kindly reach me on slack @peterrobert
### HAPPY CODING :computer:

2020-09-27 05:35 UTC, peterrobert commented on app/views/events/new.html.erb
> +    <%= f.text_field :event_date %>
This should not be a text_field there is actually a field for a date in rails

2020-09-27 05:35 UTC, peterrobert commented on config/routes.rb
> +  get '/welcome' => 'sessions#welcome'
You can make one of your routes the root route

2020-09-27 10:12 UTC, Zubenna commented on app/views/events/new.html.erb
> +    <%= f.text_field :event_date %>
The event creation method is working perfectly well on my computer if you enter the date in this format: eg 2020-08-12.

2020-09-27 15:27 UTC, Zubenna commented on config/routes.rb
> +  get '/welcome' => 'sessions#welcome'
## The get '/welcome' route has been selected as the root route.

2020-09-27 18:28 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [x] I get this error, whenever I try to create events.
![1](https://user-images.githubusercontent.com/23278161/94372614-168a0c00-00f7-11eb-800b-6a2058f2439d.png)
- [ ] Navigation links are present at the top of the page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [ ] You should write unit test for all components
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-28 10:47 UTC, Zubenna commented
# I have implemented all these changes even before now. I left clear messages in response to peterrobert's review before kobiyoyo.

## KIndly note the following once again
- ## The event creation is working perfectly well on my computer. Note that you need to create a user first by clicking on New user or Sign Up. Log into the app with your new username and click on the New Event link ontop.

![Eventcreation](https://user-images.githubusercontent.com/15705593/94423319-5b0dba00-0180-11eb-8fba-a07bef90b85c.png)

2020-09-28 11:47 UTC, stratospherique requested changes
### Great progress @Zubenna :clap: However, some changes need to be applied in order to get approval for this project. Check :arrow_down: 

#### Implementation (required) :warning: 
* [ ] Some tests are failing. Kindly fix it. Plus, regroup your specs by type (e.g models, feature, etc)
* [ ] Navigation links are missing. The user should be able to visit all the defined routes.
* [ ] When a user is logged in, "log in" and "sign up" button shouldn't be visible.
### That's it :relieved: When finished, kindly submit a code re-review request :pray: 
Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-09-28 18:00 UTC, Zubenna commented
All requested changes have been implemented.

2020-09-28 20:13 UTC, kubilaycaglayan approved these changes
Hello Team 👋
Status: Approved :green_circle: 

Great job on making the changes! :blush: 
Everything

All your tests are passing!

Please consider making these optional changes before you move on. These are extremely important details that will help you in the future. ⏬

- [ ] [OPTIONAL] Models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
💡 Consider adding more tests to cover associations.

- [ ] [OPTIONAL] There should be absolutely NO logic in views.
    >Views are only for displaying information that became available to it from its corresponding controller not generating it.

💡 Check the inline comments below please.

Good luck on your next project!
With all my respect...

2020-09-28 20:13 UTC, kubilaycaglayan commented on app/views/events/show.html.erb
> +
- [ ] [OPTIONAL] There should be absolutely NO logic in views.

2020-09-28 21:23 UTC, merged